### ISSUE TITLE
what is the reason to make role name unique per user?

### ISSUE THREAD

**Issue by xiaohuboer** [aiwaves-cn/agents#186]
![image](https://github.com/aiwaves-cn/agents/assets/55319426/d2acd8aa-2dc6-49e0-ab52-612d8fb0ba7c)
why can not use just "Architect" or "Developer"

**Comment by callanwu** [comment]
Hi, @xiaohuboer  because different roles have different tasks.
You can check:
https://github.com/aiwaves-cn/agents/blob/350246d926c41728610fba73b7703c9d65b20567/examples/Multi_Agent/software_company/config.json#L149
https://github.com/aiwaves-cn/agents/blob/350246d926c41728610fba73b7703c9d65b20567/examples/Multi_Agent/software_company/config.json#L263

**Comment by callanwu** [comment]
And we use `role` as the key for the `agent_states`. 
https://github.com/aiwaves-cn/agents/blob/350246d926c41728610fba73b7703c9d65b20567/src/agents/State.py#L144
Different agents with the same role may appear in a state.
